version: '3'
name: nest-kysely-dev
services:
  app:
    container_name: dev-nest-kysely-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    networks:
      - database
    ports:
      - '4000:${PORT}'
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      database:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  migrations:
    container_name: dev-nest-kysely-migrations
    build:
      context: .
      dockerfile: ./docker/Dockerfile.migrations
    networks:
      - database
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: ${DB_HOST}
    image: postgres
    networks:
      - database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5433:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}' ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  database:
    driver: bridge
