version: '3'
services:
  database:
    container_name: nestjs-kysely-database
    image: postgres
    ports:
      - '5433:5432'
    networks:
      - database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  database-gui:
    container_name: nestjs-kysely-pgadmin
    image: dpage/pgadmin4
    networks:
      - database
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_GUI_USER}
      - PGADMIN_DEFAULT_PASSWORD=${DB_GUI_PASSWORD}

networks:
  database:
    driver: bridge
