version: '3'
services:
  e2e:
    container_name: tests-nestjs-kysely-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - database
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=tests-nestjs-kysely-database
      - DB_PORT=5432
    depends_on:
      database:
        condition: service_healthy
    command: [ 'pnpm', 'test:e2e' ]

  database:
    container_name: tests-nestjs-kysely-database
    image: postgres
    ports:
      - '5433:5432'
    networks:
      - database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}' ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  database:
    driver: bridge
