version: '3'
name: 'nest-kysely-ci'
services:
  app:
    container_name: ci-nest-kysely-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - database
    environment:
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=ci-${DB_HOST}
      - DB_PORT=${DB_PORT}

    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: ci-${DB_HOST}
    image: postgres
    networks:
      - database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}' ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  database:
    driver: bridge
