FROM node:18.15-alpine as dev
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /usr/src/app
RUN pnpm install kysely dotenv pg @types/pg
COPY run-migrations.ts ./
COPY migrations ./migrations
CMD ["pnpm", "dlx", "ts-node", "./run-migrations.ts"]

